config:
  security:
    oauth:
      client:
        id: frontend-app
        secret: hardcoded-password-123456
      jwt:
        key: secreto_hardcodeado_123456

spring:
  zipkin:
    base-url: http://mssbce-zipkin-server:9411
    sender:
      type: rabbit
  rabbitmq:
    host: rabbitmq