spring:
  datasource:
    url: jdbc:mysql://mysql-mssbce:3306/product_mssbce_db?serverTimezone=America/Bogota
    username: root
    password: root1234@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug

